# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  default:
    - step:
        name: Archlinux Build
        image: archlinux/base:latest
        script:
          - pacman -Syy
          - pacman --noconfirm -Sy gcc pkgconf make cmake boost gtkmm
          - mkdir build && cd build
          - cmake ..
          - make